spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:oak;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: pass
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        use_sql_comments: true
        format_sql: true
        use_nationalized_character_data: true